version: '3.9'

# Services ####################################################################
services:
  # Gitlab --------------------------------------------------------------------
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.brunowillenborg.de'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 80:80
      - 443:443
      - 22:22
      - 5050:5050
    volumes:
      # - '$GITLAB_HOME/config:/etc/gitlab'
      # - '$GITLAB_HOME/logs:/var/log/gitlab'
      # - '$GITLAB_HOME/data:/var/opt/gitlab'
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
    shm_size: '256m'


# Volumes #####################################################################
volumes:

  gitlab_config:
  gitlab_data:
  gitlab_logs:
    # external: true
